### ISSUE TITLE
add proper typings for functions

### ISSUE THREAD

**Issue by galkowskit** [galkowskit/denofun#2]
Currently because of `export default curry(fnName)` all typings are lost. Either `curry` has to be typed somehow or a `.d.ts` file provided.

**Comment by KSXGitHub** [comment]
I don't think `curry` is necessary at all. I don't use curry most of the time and I don't want to pay what I don't use.

**Comment by galkowskit** [comment]
With the work done in #45, I'm going to close this. If more typings are needed separate issues should be created now.
