### ISSUE TITLE
Problems with sort function

### ISSUE THREAD

**Issue by KSXGitHub** [galkowskit/denofun#25]
1. `sort()` uses `Array.prototype.sort` https://github.com/galkowskit/denofun/blob/55d9b59ff46523a5113ba99f6ecfb3f5334abb2a/lib/sort.ts#L12
  * It mutates the array
  * It does not support non-Array

2. It does not support function returning number other than -1, 0, 1 while `Array.prototype.sort` does, for example:

```javascript
myArray.sort((a, b) => a - b)
```

**Comment by galkowskit** [comment]
That's clearly a non-intended behavior. :D
Good catch.

**Comment by KSXGitHub** [comment]
I think you should re-add "enhancement" tag:

I did say

> It does not support function returning number other than -1, 0, 1 while `Array.prototype.sort` does

What I meant is you should allow callback function to return numbers other than -1, 0, and 1, so that the following one-liner works (it already works in vanilla JavaScript, but TypeScript definition does not allow it):

```javascript
sort((a, b) => a - b, myArray)
```

**Comment by KSXGitHub** [comment]
Does sort function still mutates array

**Comment by galkowskit** [comment]
It shouldn't, no.
