### ISSUE TITLE
Shorten denoland URL by removing '/lib' from 'deno.land/x/denofun/lib/'

### ISSUE THREAD

**Issue by KSXGitHub** [galkowskit/denofun#53]
## Request

* Add `"path": "lib"` to [database.json](https://github.com/denoland/deno_website2/blob/master/src/database.json) to shorten import URL.
* Create README.md symlink inside `/lib` to make sure `deno.land/x/denofun/` display it.
* Create `/lib/lib -> .` symlink to make sure old URLs still work.

**Comment by galkowskit** [comment]
I like it! Makes the import URLs look more professional. Kudos for that!
